In [1]:
import numpy as np

In [74]:
#1.Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).
p = np.array([[1, 4, 0],
              [8, 9, 5],
              [7, 8, 7]]) 
q= np.array([1, 5, 2]) 
print("Original arrays:")
print("Array1")
print(p)
print("Array2")
print(q)
print("New Array:")
a = p + q 
print(a)

Original arrays:
Array1
[[1 4 0]
 [8 9 5]
 [7 8 7]]
Array2
[1 5 2]
New Array:
[[ 2  9  2]
 [ 9 14  7]
 [ 8 13  9]]


In [6]:
# 2.How to get the second largest value of an array when grouped by another array?
a= np.arange(10)
print("Original array:")
print(a)
np.random.shuffle(a)
n = 1
print (x[np.argsort(a)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[3]


In [30]:
# 3.How to find the position of missing values in numpy array?
x = np.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])
np.argwhere(np.isnan(x))

array([[1, 2],
       [2, 0]], dtype=int64)

In [8]:
#4.How to find the position of missing values in numpy array?
a1=np.array([[np.NaN, 1, 1], [np.NaN, np.NaN, 2]])
a2=np.nan_to_num(a1)
print(a2)

[[0. 1. 1.]
 [0. 0. 2.]]


In [9]:
#5.Write a NumPy program to create a 3x3x3 array with random values. 
a=np.random.random((3,3,3))
print(a)

[[[0.67046643 0.77330175 0.24270966]
  [0.27235486 0.16161956 0.95201118]
  [0.19966753 0.07783617 0.51366931]]

 [[0.72434299 0.10447032 0.66908041]
  [0.00974872 0.50461865 0.61913772]
  [0.29982351 0.75117514 0.75172406]]

 [[0.35000553 0.28302965 0.35465263]
  [0.28041685 0.9796554  0.99845742]
  [0.55785279 0.50159886 0.65607434]]]


In [11]:
#6.Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
a3=np.random.random(15)
print("Original array:")
print(a3)
a3[a3.argmax()]=-1
print("Maximum value replaced by -1:")
print(a3)

Original array:
[0.52734599 0.82907907 0.30603462 0.37901624 0.3869507  0.85707995
 0.3883426  0.51528393 0.10258771 0.34935695 0.19833731 0.31930673
 0.63350169 0.52449066 0.77586065]
Maximum value replaced by -1:
[ 0.52734599  0.82907907  0.30603462  0.37901624  0.3869507  -1.
  0.3883426   0.51528393  0.10258771  0.34935695  0.19833731  0.31930673
  0.63350169  0.52449066  0.77586065]


In [14]:
#6.Write a NumPy program to get the unique elements of an array.
a4=np.array([[9, 1], [9, 8]])
print("Original array:")
print(a4)
print("Unique elements of the above array:")
print(np.unique(a4))

Original array:
[[9 1]
 [9 8]]
Unique elements of the above array:
[1 8 9]


In [16]:
#7.Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
a5 = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(a5)
print("Values bigger than 10 =", a5[a5>10])

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]


In [17]:
a6= np.arange(7)
print("Original array")
print(a6)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(a6, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [20]:
#8.Write a NumPy program to remove the negative values in a NumPy array with 0.
a8=np.array([-9,-4,0,21,7,8,2,-5])
print("Original array:")
print(a8)
print("Replace the negative values of the said array with 0:")
a8[a8<0]=0
print(a8)

Original array:
[-9 -4  0 21  7  8  2 -5]
Replace the negative values of the said array with 0:
[ 0  0  0 21  7  8  2  0]


In [21]:
#9.Write a NumPy program to calculate the absolute value element-wise.
a9=np.array([-12.8,4.8,.54])
print("Original array:")
print(a9)
print("Element-wise absolute value:")
print(np.absolute(a9))

Original array:
[-12.8    4.8    0.54]
Element-wise absolute value:
[12.8   4.8   0.54]


In [80]:
#10.Write a NumPy program to replace odd number in 2d array by its square . 
a10=np.array([1,2,3,4,5,6,7,8,9,10]) 
print(np.where(a10%2!=0,a10**2,a10)) 
#print(a10)




[ 1  2  9  4 25  6 49  8 81 10]


Assignment no-2


In [37]:
#1.Write a NumPy program to test element-wise for NaN of a given array.
a=np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


In [39]:
#2.Write a NumPy program to compute the inner product of two given vectors .
a1=np.array([4,4])
b1=np.array([1,16])
print("Original vectors:")
print(a1)
print(b1)
print("Inner product of said vectors:")
print(np.dot(a1,b1))

Original vectors:
[4 4]
[ 1 16]
Inner product of said vectors:
68


In [40]:
#3.Write a NumPy program to create an array with values ranging from 12 to 38.
x=np.arange(12,38)
print(x)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [42]:
#4.Write a NumPy program to reverse an array (first element becomes last).
print("Reverse array:")
x = x[::-1]
print(x)

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [45]:
#5.Write a NumPy program to convert an array to a float type.
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [48]:
#6.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
x = np.ones((3,3))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [51]:
#7. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  Checkerboard pattern:
x1=np.ones((3,3))
print("Checkerboard pattern:")
x1=np.zeros((8,8),dtype=int)
x1[1::2,::2]=1
x1[::2,1::2]=1
print(x1)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [54]:
#8.Write a NumPy program to append values to the end of an array.
x = [5,8,9]
print("Original array:")
print(x)
x = np.append(x, [[5,8,9], [6,7,9]])
print("After append values to the end of the array:")
print(x)

Original array:
[5, 8, 9]
After append values to the end of the array:
[5 8 9 5 8 9 6 7 9]


In [56]:
#9.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
array1 = np.array([1,5,8,7,9,6,45,4])
print("Array1: ",array1)
array2 = [9,6]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 1  5  8  7  9  6 45  4]
Array2:  [9, 6]
Compare each element of array1 and array2
[False False False False  True  True False False]


In [58]:
#10.Write a NumPy program to get the unique elements of an array
x = np.array([1,5,8,9,1,5,7,3,2])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[1 5 8 9 1 5 7 3 2]
Unique elements of the above array:
[1 2 3 5 7 8 9]


In [59]:
#11.Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


In [60]:
#12.Write a NumPy program to create a contiguous flattened array
x = np.array([[11,55,78],[1,2,6]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)


Original array:
[[11 55 78]
 [ 1  2  6]]
New flattened array:
[11 55 78  1  2  6]


In [62]:
#13.Write a NumPy program to concatenate two 2-dimensional arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.concatenate((a, b), 1)
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [63]:
#14.Write a NumPy program to convert 1-D arrays as columns into a 2-D array. 
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


In [65]:
#15.Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100. 
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [66]:
#16.Write a NumPy program to get the index of a maximum element in a NumPy array along one axis.
a = np.array([[1,2,3],[4,5,6]])
print("Original array:")
print(a)
i,j = np.unravel_index(a.argmax(), a.shape)
print("Index of a maximum element in a numpy array along one axis:")
print(a[i,j])

Original array:
[[1 2 3]
 [4 5 6]]
Index of a maximum element in a numpy array along one axis:
6


In [68]:
#17.Write a NumPy program to stack 1-D arrays as row wise. 
a=np.array((1,2,3))
b=np.array((4,5,6))
print("Array-1")
print(a)
print("Array-2")
print(b)
c=np.row_stack((a,b))
print("\nStack 1-D arrays as rows wise:")
print(c)

Array-1
[1 2 3]
Array-2
[4 5 6]

Stack 1-D arrays as rows wise:
[[1 2 3]
 [4 5 6]]


In [69]:
#18.Write a NumPy program to get the minimum and maximum value of a given array along the second axis. 
x=np.arange(4).reshape((2,2))
print("\nOriginal array:")
print(x)
print("\nMaximum value along the second axis:")
print(np.amax(x, 1))
print("Minimum value along the second axis:")
print(np.amin(x, 1))


Original array:
[[0 1]
 [2 3]]

Maximum value along the second axis:
[1 3]
Minimum value along the second axis:
[0 2]
